name: Main CI

on:
  pull_request:
    branches:
      - "**"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: package.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
